apiVersion: v1
kind: Service
metadata:
  name: beginner-html-site-styled-service
spec:
  selector:
    app: beginner-html-site-styled
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010
  type: NodePort
